name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t muhdlai08/tryanderror:v1 .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Push Docker image
        run: |
          docker push muhdlai08/tryanderror:v1

      - name: Run Docker image container
        run: |
          docker run -d --rm -p 8080:8080 muhdlai08/tryanderror:v1
